#!/bin/bash
# /etc/init.d/lights

### BEGIN INIT INFO
# Provides:          lights
# Required-Start:	$network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This service is used to manage lights
### END INIT INFO

case "$1" in
	start)
		nohup stdbuf -oL sudo python3 /opt/ir_lights/launcher.py >/opt/ir_lights/log.log 2>&1 &
		;;
	stop)
		sudo killall python3
		;;
	*)
		exit 1
		;;
esac

exit 0
